baseURL = 'https://leeT-42.github.io/LTM/'
languageCode = 'vi'
title = 'Lê Minh Thanh'
theme = 'PaperMod'

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  
  [params.profileMode]
    enabled = true
    title = "Lê Minh Thanh"
    subtitle = "Developer | Network Enthusiast | Java Learner"
    imageUrl = "https://github.com/leeT-42.png" 
    imageTitle = "Avatar"
    buttons = [
       { name = "Home", url = "/LTM/" },
      { name = "Projects", url = "/LTM/projects" },
      { name = "Blog", url = "/LTM/posts" },
      { name = "About", url = "/LTM/about" },
    ]

  [[params.socialIcons]]
    name = "Github"
    url = "https://github.com/leeT-42"
  [[params.socialIcons]]
    name = "Email"
    url = "mailto:leminhthanh931@gmail.com"
    # Facebook = "https://facebook.com/username" 
    # LinkedIn = "https://linkedin.com/in/username"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    pageRef = "/"
    weight = 10
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    pageRef = "projects"
    weight = 15
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    pageRef = "posts"
    weight = 20
  [[menu.main]]
    identifier = "about"
    name = "About"
    pageRef = "about"
    weight = 30
