baseURL = 'https://leeT-42.github.io/LTM/'
languageCode = 'vi'
title = 'Lê Minh Thành'
theme = 'PaperMod'

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  
  [params.profileMode]
    enabled = true
    title = "Lê Minh Thành"
    subtitle = "Developer | Network Enthusiast | Java Learner"
    imageUrl = "https://github.com/leeT-42.png" 
    imageTitle = "Avatar"
    buttons = [
      { name = "Projects", url = "/projects" },
      { name = "Blog", url = "/posts" },
      { name = "About", url = "/about" },
    ]

  [params.socialIcons]
    Github = "https://github.com/leeT-42"
    Email = "mailto:leminhthanh931@gmail.com"
    # Facebook = "https://facebook.com/username" 
    # LinkedIn = "https://linkedin.com/in/username"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects"
    weight = 15
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/posts"
    weight = 20
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 30
