baseURL = 'https://leeT-42.github.io/LTM/'
languageCode = 'vi'
title = 'LÃª Minh Thanh'
theme = 'PaperMod'
summaryLength = 10

[params]
  defaultTheme = "auto"
  ShowReadingTime = false
  ShowShareButtons = false
  ShareButtons = ["linkedin", "email"]
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = false
  hideMeta = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
  
  [params.profileMode]
    enabled = true
    title = "ChÃ o má»«ng Ä‘áº¿n vá»›i Blog cá»§a LÃª Minh Thanh ğŸ‘‹"
    subtitle = """
Äam mÃª chia sáº» kiáº¿n thá»©c thá»±c chiáº¿n vá»:
- ğŸŒ **Láº­p trÃ¬nh Máº¡ng** | âš¡ **Multithreading** | ğŸ›ï¸ **Há»‡ thá»‘ng PhÃ¢n tÃ¡n**

Blog cÃ¡ nhÃ¢n - NÆ¡i káº¿t ná»‘i vÃ  cÃ¹ng nhau phÃ¡t triá»ƒn!
"""
    imageUrl = "images/profile-portrait.png"
    imageTitle = "Hello"
    buttons = [
       { name = "ğŸš€ KHÃM PHÃ NGAY", url = "posts" },
       { name = "ğŸ“‚ Dá»° ÃN Cá»¦A TÃ”I", url = "projects" },
    ]

 
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    pre = "ğŸ  "
    pageRef = "/"
    weight = 10
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    pre = "ğŸ“½ï¸ "
    pageRef = "projects"
    weight = 15
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    pre = "ğŸ“° "
    pageRef = "posts"
    weight = 20
  [[menu.main]]
    identifier = "about"
    name = "About"
    pre = "ğŸ‘¨â€ğŸ’» "
    pageRef = "about"
    weight = 30
  [[menu.main]]
    identifier = "search"
    name = "Search"
    pageRef = "search"
    weight = 5
  
disqusShortname = 'leminhthanh-ltm'
